//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SortingPlugin {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class PluginSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PluginSettings defaultInstance = ((PluginSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PluginSettings())));
        
        public static PluginSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Show the individual area Pokedéxes for those that have it.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Show the individual area Pokedéxes for those that have it.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 显示个人图鉴 {
            get {
                return ((bool)(this["显示个人图鉴"]));
            }
            set {
                this["显示个人图鉴"] = value;
            }
        }
        
        /// <summary>
        /// The box to begin sorting from.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The box to begin sorting from.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int 盒子排序结束 {
            get {
                return ((int)(this["盒子排序结束"]));
            }
            set {
                this["盒子排序结束"] = value;
            }
        }
        
        /// <summary>
        /// The box to ending sorting in.  -1 can be used to specify the last box.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The box to ending sorting in.  -1 can be used to specify the last box.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int 盒子排序开始 {
            get {
                return ((int)(this["盒子排序开始"]));
            }
            set {
                this["盒子排序开始"] = value;
            }
        }
    }
}
